# Generated by Django 2.2.4 on 2019-08-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Licence', 'Licence'), ('Magister', 'Magister'), ('Bacharel', 'Bacharel'), (' Licenciado', 'Licenciado'), ('Doutorado', 'Doutorado'), ('Bachelor degree', 'Bachelor degree'), ('Bachelor degree (Honours)', 'Bachelor degree (Honours)'), ('Master’s degree', 'Master’s degree')], max_length=100)),
                ('country', models.CharField(choices=[('Algeria', 'Algeria'), ('Angola', 'Angola'), ('Australia', 'Australia')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UCTDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.UCTDegree')),
            ],
        ),
    ]
