# Generated by Django 2.2.4 on 2019-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20190826_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
