# Generated by Django 2.2.4 on 2019-08-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF Upload'),
        ),
    ]
