# Generated by Django 2.2.4 on 2019-08-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20190830_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='thesis',
            field=models.BooleanField(default=False),
        ),
    ]
