# Generated by Django 2.2.4 on 2019-08-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_qualification_thesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgradprofile',
            name='qualification',
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Qualification'),
        ),
    ]
