# Generated by Django 2.2.4 on 2019-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20190831_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgradprofile',
            name='citizenship',
            field=models.CharField(choices=[('RSA-Citizen', 'RSA-Citizen'), ('RSA-Permanent-Resident', 'RSA-Permanent-Resident'), ('International', 'International')], default='International', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgradprofile',
            name='citizenship_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postgradprofile',
            name='current_city',
            field=models.CharField(default='Jozi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgradprofile',
            name='current_country',
            field=models.CharField(default='SA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgradprofile',
            name='race',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Coloured', 'Coloured'), ('Indian', 'Indian'), ('White', 'White')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='my@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='mr', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
