# Generated by Django 2.2.4 on 2019-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20190903_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
